### ISSUE TITLE
Scene Transition needs smoothing

### ISSUE THREAD

**Issue by SimonDarksideJ** [provencher/MR_Surfaces_Oculus#1]
Currently, the Quest is freezing between scene changes. This needs resolving as it becomes very sharing, with also the drawing between each eye being offset until the new scene has launched.

Ideally, needs a fade to black or muting everything in the scene (including menu) apart from maybe the hands, so the scene loads without rendering.

**Comment by provencher** [comment]
Yeah this can be solved using the Oculus Overlay. I can probably add it with ease, but I didn't get around to it.

**Comment by provencher** [comment]
Mitigated in PR #4
